package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1



/**
 * Chats generated by hbm2java
 */
public class Chats  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuariosByUsuario1Id;
     private Usuarios usuariosByUsuario2Id;

    public Chats() {
    }

	
    public Chats(Usuarios usuariosByUsuario1Id, Usuarios usuariosByUsuario2Id) {
        this.usuariosByUsuario1Id = usuariosByUsuario1Id;
        this.usuariosByUsuario2Id = usuariosByUsuario2Id;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuariosByUsuario1Id() {
        return this.usuariosByUsuario1Id;
    }
    
    public void setUsuariosByUsuario1Id(Usuarios usuariosByUsuario1Id) {
        this.usuariosByUsuario1Id = usuariosByUsuario1Id;
    }
    public Usuarios getUsuariosByUsuario2Id() {
        return this.usuariosByUsuario2Id;
    }
    
    public void setUsuariosByUsuario2Id(Usuarios usuariosByUsuario2Id) {
        this.usuariosByUsuario2Id = usuariosByUsuario2Id;
    }




}


