package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Coincidencias generated by hbm2java
 */
public class Coincidencias  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuariosByUsuario1Id;
     private Usuarios usuariosByUsuario2Id;
     private double compatibilidad;
     private Date fechaCoincidencia;
     private boolean likeUsuario1;
     private boolean likeUsuario2;

    public Coincidencias() {
    }

    public Coincidencias(Usuarios usuariosByUsuario1Id, Usuarios usuariosByUsuario2Id, double compatibilidad, Date fechaCoincidencia, boolean likeUsuario1, boolean likeUsuario2) {
       this.usuariosByUsuario1Id = usuariosByUsuario1Id;
       this.usuariosByUsuario2Id = usuariosByUsuario2Id;
       this.compatibilidad = compatibilidad;
       this.fechaCoincidencia = fechaCoincidencia;
       this.likeUsuario1 = likeUsuario1;
       this.likeUsuario2 = likeUsuario2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuariosByUsuario1Id() {
        return this.usuariosByUsuario1Id;
    }
    
    public void setUsuariosByUsuario1Id(Usuarios usuariosByUsuario1Id) {
        this.usuariosByUsuario1Id = usuariosByUsuario1Id;
    }
    public Usuarios getUsuariosByUsuario2Id() {
        return this.usuariosByUsuario2Id;
    }
    
    public void setUsuariosByUsuario2Id(Usuarios usuariosByUsuario2Id) {
        this.usuariosByUsuario2Id = usuariosByUsuario2Id;
    }
    public double getCompatibilidad() {
        return this.compatibilidad;
    }
    
    public void setCompatibilidad(double compatibilidad) {
        this.compatibilidad = compatibilidad;
    }
    public Date getFechaCoincidencia() {
        return this.fechaCoincidencia;
    }
    
    public void setFechaCoincidencia(Date fechaCoincidencia) {
        this.fechaCoincidencia = fechaCoincidencia;
    }
    public boolean isLikeUsuario1() {
        return this.likeUsuario1;
    }
    
    public void setLikeUsuario1(boolean likeUsuario1) {
        this.likeUsuario1 = likeUsuario1;
    }
    public boolean isLikeUsuario2() {
        return this.likeUsuario2;
    }
    
    public void setLikeUsuario2(boolean likeUsuario2) {
        this.likeUsuario2 = likeUsuario2;
    }




}


