package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * Facultades generated by hbm2java
 */
public class Facultades  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set usuarioses = new HashSet(0);

    public Facultades() {
    }

	
    public Facultades(String nombre) {
        this.nombre = nombre;
    }
    public Facultades(String nombre, Set usuarioses) {
       this.nombre = nombre;
       this.usuarioses = usuarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


