package modelos;
// Generated 30-abr-2023 16:34:45 by Hibernate Tools 4.3.1



/**
 * Intereses generated by hbm2java
 */
public class Intereses  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public Intereses() {
    }

    public Intereses(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


