package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personalidades generated by hbm2java
 */
public class Personalidades  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set usuarioPersonalidadeses = new HashSet(0);

    public Personalidades() {
    }

	
    public Personalidades(String nombre) {
        this.nombre = nombre;
    }
    public Personalidades(String nombre, Set usuarioPersonalidadeses) {
       this.nombre = nombre;
       this.usuarioPersonalidadeses = usuarioPersonalidadeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarioPersonalidadeses() {
        return this.usuarioPersonalidadeses;
    }
    
    public void setUsuarioPersonalidadeses(Set usuarioPersonalidadeses) {
        this.usuarioPersonalidadeses = usuarioPersonalidadeses;
    }




}


