package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TarjetasDeCredito generated by hbm2java
 */
public class TarjetasDeCredito  implements java.io.Serializable {


     private Integer idTarjeta;
     private Usuarios usuarios;
     private String numeroTarjeta;
     private Date fechaExpiracion;
     private String cvv;

    public TarjetasDeCredito() {
    }

    public TarjetasDeCredito(Usuarios usuarios, String numeroTarjeta, Date fechaExpiracion, String cvv) {
       this.usuarios = usuarios;
       this.numeroTarjeta = numeroTarjeta;
       this.fechaExpiracion = fechaExpiracion;
       this.cvv = cvv;
    }
   
    public Integer getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(Integer idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }




}


