package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TarjetasDeCredito generated by hbm2java
 */
public class TarjetasDeCredito  implements java.io.Serializable {


     private Integer idTarjeta;
     private Usuarios usuarios;
     private String numeroTarjeta;
     private String mes;
     private String anio;
     private String cvv;
     private String titular;

    public TarjetasDeCredito() {
    }

    public TarjetasDeCredito(Usuarios usuarios,String titular, String numeroTarjeta, String cvv,String mes, String anio) {
       this.usuarios = usuarios;
       this.numeroTarjeta = numeroTarjeta;
       this.cvv = cvv;
       this.anio = anio;
       this.mes = mes;
       this.titular = titular;
    }
   
    public Integer getIdTarjeta() {
        return this.idTarjeta;
    }

    public String getTitular() {
        return titular;
    }

    public void setTitular(String titular) {
        this.titular = titular;
    }
    
    public void setIdTarjeta(Integer idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
 
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    public String getMes() {
        return mes;
    }

    public void setMes(String mes) {
        this.mes = mes;
    }

    public String getAnio() {
        return anio;
    }

    public void setAnio(String anio) {
        this.anio = anio;
    }




}


