package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1



/**
 * UsuarioIntereses generated by hbm2java
 */
public class UsuarioIntereses  implements java.io.Serializable {


     private Integer id;
     private Intereses intereses;
     private Usuarios usuarios;

    public UsuarioIntereses() {
    }

    public UsuarioIntereses(Intereses intereses, Usuarios usuarios) {
       this.intereses = intereses;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Intereses getIntereses() {
        return this.intereses;
    }
    
    public void setIntereses(Intereses intereses) {
        this.intereses = intereses;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


