package modelos;
// Generated 01-may-2023 0:06:26 by Hibernate Tools 4.3.1



/**
 * UsuarioPersonalidades generated by hbm2java
 */
public class UsuarioPersonalidades  implements java.io.Serializable {


     private Integer id;
     private Personalidades personalidades;
     private Usuarios usuarios;

    public UsuarioPersonalidades() {
    }

    public UsuarioPersonalidades(Personalidades personalidades, Usuarios usuarios) {
       this.personalidades = personalidades;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Personalidades getPersonalidades() {
        return this.personalidades;
    }
    
    public void setPersonalidades(Personalidades personalidades) {
        this.personalidades = personalidades;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


